#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------------------
# test_sensitivity.sh
#
# Grid-search / sensitivity test driver for DSG on the DEEP/Wikipedia datasets.
#
# What it does:
# - Iterates a parameter grid over:
#   - M (a.k.a. out-degree, passed to apps/build_index as -k)
#   - ef_construction (passed as -ef_construction)
#   - ef_max (passed as -ef_max)
#   - alpha (passed as -alpha)
# - For each configuration:
#   1) Builds an index with apps/build_index (skips if index file exists)
#   2) Runs apps/query_index against the matching groundtruth (skips if query log exists)
#
# Defaults:
# - DATASET=deep
# - DATA_SIZE=100000 (must match a groundtruth set under $GROUNDTRUTH_ROOT/$DATASET)
# - QUERY_NUM=1000, QUERY_K=10 (must match groundtruth files)
#
# Usage examples:
#   # Run full grid (build + query) with default lists
#   bash scripts/test_sensitivity.sh
#
#   # Only build indexes (skip query)
#   SKIP_QUERY=1 bash scripts/test_sensitivity.sh
#
#   # Only query already-built indexes with a fixed search ef (no sweep)
#   SKIP_BUILD=1 SEARCH_EF=128 bash scripts/test_sensitivity.sh
#
#   # Override grids
#   M_LIST="12 16" EFC_LIST="100 130" EFM_LIST="300 400" ALPHA_LIST="1.0 1.1" \
#     bash scripts/test_sensitivity.sh
#
# Notes:
# - This script runs configurations sequentially. On a cluster, consider running
#   multiple copies with disjoint grids or using SLURM job arrays.
# - Groundtruth files are expected to follow the naming convention generated by
#   apps/generate_groundtruth (see src/utils/data_wrapper.cc).
# ------------------------------------------------------------------------------

find_repo_root() {
  # Walk up a few levels to locate the project root (the directory that contains
  # CMakeLists.txt and scripts/). This is important for SLURM because sbatch
  # copies the job script into /var/spool/slurmd, so BASH_SOURCE[0] may not sit
  # inside the real project directory.
  local start_dir="$1"
  local dir="${start_dir}"
  for _ in 1 2 3 4 5 6 7; do
    if [[ -f "${dir}/CMakeLists.txt" && -d "${dir}/scripts" ]]; then
      echo "${dir}"
      return 0
    fi
    dir="$(dirname "${dir}")"
  done
  return 1
}

# ROOT_DIR resolution priority:
# 1) User-provided ROOT_DIR (recommended for cluster runs)
# 2) SLURM_SUBMIT_DIR (when launched by sbatch), plus upward search
# 3) Script-relative path (works for interactive runs: bash scripts/test_sensitivity.sh)
if [[ -n "${ROOT_DIR:-}" ]]; then
  ROOT_DIR="$(cd "${ROOT_DIR}" && pwd)"
elif [[ -n "${SLURM_SUBMIT_DIR:-}" ]]; then
  if ROOT_DIR="$(find_repo_root "${SLURM_SUBMIT_DIR}")"; then
    :
  else
    ROOT_DIR="$(cd "${SLURM_SUBMIT_DIR}" && pwd)"
  fi
else
  ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
BUILD_DIR="${BUILD_DIR:-${ROOT_DIR}/build}"
BUILD_BIN="${BUILD_DIR}/apps/build_index"
QUERY_BIN="${BUILD_DIR}/apps/query_index"

# Toggle the default dataset here (you can still override via env:
# `DATASET=deep bash scripts/test_sensitivity.sh`).
DEFAULT_DATASET="wikipedia"
# DEFAULT_DATASET="deep"
DATASET="${DATASET:-${DEFAULT_DATASET}}"

# Dataset-specific default paths (can still be overridden via DATASET_PATH/QUERY_PATH env vars).
declare -A DEFAULT_DATASET_PATHS=(
  ["deep"]="${ROOT_DIR}/data/deep10M.bin"
  ["wikipedia"]="${ROOT_DIR}/data/wiki_image_embedding.bin"
)
declare -A DEFAULT_QUERY_PATHS=(
  ["deep"]="${ROOT_DIR}/data/deep_query.bin"
  ["wikipedia"]="${ROOT_DIR}/data/wiki_image_query.bin"
)

DATASET_PATH="${DATASET_PATH:-${DEFAULT_DATASET_PATHS[${DATASET}]:-}}"
QUERY_PATH="${QUERY_PATH:-${DEFAULT_QUERY_PATHS[${DATASET}]:-}}"
GROUNDTRUTH_ROOT="${GROUNDTRUTH_ROOT:-${ROOT_DIR}/groundtruth/static}"

DATA_SIZE="${DATA_SIZE:-100000}"
QUERY_NUM="${QUERY_NUM:-1000}"
QUERY_K="${QUERY_K:-10}"
SEARCH_EF="${SEARCH_EF:-}" # empty => use query_index's default sweep
SEED="${SEED:-2025}"

# Control switches:
# - SKIP_BUILD=1: do not run build_index
# - SKIP_QUERY=1: do not run query_index
# - FORCE=1: rebuild index and overwrite logs even if they exist
SKIP_BUILD="${SKIP_BUILD:-0}"
SKIP_QUERY="${SKIP_QUERY:-0}"
FORCE="${FORCE:-0}"

# Parameter grids (space-separated lists). Override via environment variables.
M_LIST="${M_LIST:-"24 32 48"}"
EFC_LIST="${EFC_LIST:-"130 160 190"}"
# NOTE: The user request did not specify EFMax values explicitly.
# Defaulting to a reasonable sweep around common values; override EFM_LIST if needed.
EFM_LIST="${EFM_LIST:-"300 500 600"}"
ALPHA_LIST="${ALPHA_LIST:-"1.0 1.1 1.2"}"

LOG_ROOT="${LOG_ROOT:-${ROOT_DIR}/logs/${DATASET}/sensitivity}"
INDEX_DIR="${ROOT_DIR}/index/${DATASET}"

configure_and_build() {
  cmake -S "${ROOT_DIR}" -B "${BUILD_DIR}"
  cmake --build "${BUILD_DIR}" --target build_index query_index
}

die() {
  echo "[DSG][FATAL] $*" >&2
  exit 1
}

require_file() {
  local path="$1"
  [[ -f "${path}" ]] || die "Required file not found: ${path}"
}

require_dir() {
  local path="$1"
  [[ -d "${path}" ]] || die "Required directory not found: ${path}"
}

echo "[DSG] ROOT_DIR=${ROOT_DIR}"
echo "[DSG] BUILD_DIR=${BUILD_DIR}"
echo "[DSG] DATASET=${DATASET} N=${DATA_SIZE} QUERY_NUM=${QUERY_NUM} QUERY_K=${QUERY_K}"

require_file "${DATASET_PATH}"
require_file "${QUERY_PATH}"
require_dir "${GROUNDTRUTH_ROOT}"

# Ensure groundtruth exists for this dataset + (N, query_num, query_k).
GT_DATASET_DIR="${GROUNDTRUTH_ROOT}/${DATASET}"
require_dir "${GT_DATASET_DIR}"
GT_SENTINEL="${GT_DATASET_DIR}/range_01pct_top${QUERY_K}_q${QUERY_NUM}_N${DATA_SIZE}_neighbors.bin"
require_file "${GT_SENTINEL}"

if [[ ! -x "${BUILD_BIN}" || ! -x "${QUERY_BIN}" ]]; then
  echo "[DSG] build/query binaries not found, building..."
  configure_and_build
fi
[[ -x "${BUILD_BIN}" ]] || die "Binary not executable: ${BUILD_BIN}"
[[ -x "${QUERY_BIN}" ]] || die "Binary not executable: ${QUERY_BIN}"

mkdir -p "${INDEX_DIR}"
mkdir -p "${LOG_ROOT}/build" "${LOG_ROOT}/search"

read -r -a MS <<< "${M_LIST}"
read -r -a EFCS <<< "${EFC_LIST}"
read -r -a EFMS <<< "${EFM_LIST}"
read -r -a ALPHAS <<< "${ALPHA_LIST}"

total=0
for m in "${MS[@]}"; do
  for efc in "${EFCS[@]}"; do
    for efm in "${EFMS[@]}"; do
      for alpha in "${ALPHAS[@]}"; do
        total=$((total + 1))
      done
    done
  done
done
echo "[DSG] Configurations to run: ${total}"
echo "[DSG] M_LIST=${M_LIST}"
echo "[DSG] EFC_LIST=${EFC_LIST}"
echo "[DSG] EFM_LIST=${EFM_LIST}"
echo "[DSG] ALPHA_LIST=${ALPHA_LIST}"
if [[ -n "${SEARCH_EF}" ]]; then
  echo "[DSG] SEARCH_EF=${SEARCH_EF} (single value)"
else
  echo "[DSG] SEARCH_EF= (using query_index default sweep)"
fi

run_id=0
for m in "${MS[@]}"; do
  for efc in "${EFCS[@]}"; do
    for efm in "${EFMS[@]}"; do
      for alpha in "${ALPHAS[@]}"; do
        run_id=$((run_id + 1))
        base="${DATASET}_N${DATA_SIZE}_k${m}_efc${efc}_efm${efm}_alpha${alpha}"
        index_path="${INDEX_DIR}/${base}.index"
        build_log="${LOG_ROOT}/build/${base}.log"
        search_log="${LOG_ROOT}/search/${base}"
        if [[ -n "${SEARCH_EF}" ]]; then
          search_log="${search_log}_ef${SEARCH_EF}"
        fi
        search_log="${search_log}.log"

        echo
        echo "[DSG] ===== (${run_id}/${total}) ${base} ====="
        echo "[DSG] index_path=${index_path}"

        if [[ "${SKIP_BUILD}" -eq 0 ]]; then
          if [[ -f "${index_path}" && "${FORCE}" -eq 0 ]]; then
            echo "[DSG] Build: SKIP (index exists)"
          else
            echo "[DSG] Build: RUN -> ${build_log}"
            /usr/bin/time -v "${BUILD_BIN}" \
              -dataset "${DATASET}" \
              -N "${DATA_SIZE}" \
              -dataset_path "${DATASET_PATH}" \
              -query_path "${QUERY_PATH}" \
              -index_path "${index_path}" \
              -k "${m}" \
              -ef_construction "${efc}" \
              -ef_max "${efm}" \
              -alpha "${alpha}" \
              -seed "${SEED}" | tee "${build_log}"
          fi
        else
          echo "[DSG] Build: SKIP (SKIP_BUILD=1)"
        fi

        if [[ "${SKIP_QUERY}" -eq 0 ]]; then
          if [[ ! -f "${index_path}" ]]; then
            die "Query requested but index file missing: ${index_path}"
          fi
          if [[ -f "${search_log}" && "${FORCE}" -eq 0 ]]; then
            echo "[DSG] Query: SKIP (log exists)"
          else
            echo "[DSG] Query: RUN -> ${search_log}"
            cmd_args=(
              -dataset "${DATASET}"
              -N "${DATA_SIZE}"
              -dataset_path "${DATASET_PATH}"
              -query_path "${QUERY_PATH}"
              -index_path "${index_path}"
              -groundtruth_root "${GROUNDTRUTH_ROOT}"
              -query_num "${QUERY_NUM}"
              -query_k "${QUERY_K}"
            )
            if [[ -n "${SEARCH_EF}" ]]; then
              cmd_args+=(-search_ef "${SEARCH_EF}")
            fi
            "${QUERY_BIN}" "${cmd_args[@]}" | tee "${search_log}"
          fi
        else
          echo "[DSG] Query: SKIP (SKIP_QUERY=1)"
        fi
      done
    done
  done
done

echo
echo "[DSG] All done. Logs under: ${LOG_ROOT}"


